templates/account/login.html, templates/account/logout.html, templates/account/signup.html
Modificación en las plantillas agregado de clases para centrado y botón en cerrar sesión
=> #188 modificacion de templates login,logout,signup

jobs/migrations/0003_job_slug.py, jobs/models.py, jobs/urls.py, requirements.txt
=> Agregar url amigable con título de la oferta de trabajo en vez del id (SEO related)

community/templates/footer.html, static/css/styles.css
Fixes for https://github.com/PyAr/pyarweb/issues/249
=> [249] Top padding for items in main content. Footer items placement.

jobs/urls.py, jobs/views.py, templates/jobs/_jobs_tags.html, templates/jobs/job_detail.html, templates/jobs/job_list.html
=> fix para le issue #232

jobs/models.py
Hi! newbie here, but maybe I could help with this.
=> Ordering job by modified date

community/templates/header.html, templates/events/event_list.html
eso mismo, me parece que esta bueno que te redireccione a donde estabas antes de loguearte/registrarte
=> redireccion al mismo lugar donde se estaba despues de loguear/registrar

bootstrap.sh
=> Actualizar caché de paquetes apt antes de instalar

CONTRIBUTING.md, README.md
- Editando / Ordenando README.md.
- Agregando CONTRIBUTING.md para especificar como trabajar
con una calidad mínima aceptable.
=> Cambios en la documentación (#293):

community/templates/base_site.html
Se realiza en base al issue #311, si  bien esto va a configurar el idoma por defecto pero hay que modificar el server "mailman" para que el email que llegue sea en español.
=> Se agrega idioma al form de suscripcion a la lista de correo.

CONTRIBUTING.md
Cambio chico en CONTRIBUTING.MD para mejorar legibilidad
https://github.com/PyAr/pyarweb/issues/352
Se uso ``` como segunda opcion en base a lo mencionado en https://guides.github.com/features/mastering-markdown/
=> Resuelvo issue-352

community/templates/community/index.html
=> Fix issue #358

Makefile, README.md, docker-compose.yml
- Now dockerhub will build a dockerimage from master and dev for each push to the respective branch.
- Makefile to run docker-compose commands. 
- wiki updated --> https://github.com/PyAr/pyarweb/wiki/Instalacion-con-Docker
=> use docker image from dockerhub

events/forms.py, events/migrations/0003_eventparticipation_gender.py, events/models.py, events/views.py, templates/events/eventparticipation_list.html
=> Agrego el campo género en inscripción a eventos

community/templates/community/index.html, community/tests/test_homepage.py, community/views.py, jobs/tests/factories.py, news/tests/factories.py
Este branch implementa la propuesta en #397 
Pueden revisarlo para ver cómo queda. Por ejemplo:
=> 397 unify news jobs events widget

Makefile, dev_requirements.txt, events/migrations/0004_auto_20180428_1949.py, jobs/migrations/0003_normalize_tags_20180428_1955.py, jobs/utils.py, pyarweb/settings.py
Este issue closes #407 , complementando lo que se hizo hace un rato.
=> 407 migration to fix tags

events/forms.py, events/migrations/0004_auto_20180429_1546.py, events/models.py, events/tests/test_views.py, events/urls.py
En este pull con @samsagaz agregamos el feature de poder acceder a eventos a través de slugs!
this pull closed #346
=> #346 autoslug

events/migrations/0005_auto_20180429_1546.py
@litox podemos mergear esto, dev falla por conflicto de migraciones
=> Fixed migrations

.github/workflows/ISSUE_TEMPLATE/bug_report.yml, pull_request_template.md
- Se incorpora una plantilla de incidencia, para solicitar información a las personas que quieran crear un informe de error. La plantilla pide que se completen los datos para crear eficientemente el informe y poder resolverlo, teniendo la información necesaria para poder resolver el problema.
- https://github.com/PyAr/pyarweb/issues/508
=> Incorporation of an issues template

static/css/styles.css
Carga los fonts usando HTTPS. Dejo tambien el de HTTP para el entorno de desarollo
=> Load fonts using https

templates/irc/irc.html
-  Apuntar al canal #pyar en Libera Chat
- Closes
- Probé la URL del widget -que a diferencia de la anterior, tiene puerto- y anda bien
1.
2.
3.
Gracias por contribuir con el proyecto.
Estamos pendiente de revisar los cambios propuestos.
=> Point to Libera Chat channel

events/views.py
-  Django 3.X migration, `is_authenticated` changed from being a method to just a boolean attribute. That is why there are so many Sentry errors https://pyar.sentry.io/issues/2535174281/?project=1474214&query=is%3Aunresolved&referrer=issue-stream&stream_index=1
=> Update is_authenticated because it is a boolean

community/templates/community/index.html, community/templates/header.html, joboffers/templates/joboffers/_tags.html, joboffers/tests/test_joboffer_validations.py, joboffers/tests/test_views.py, joboffers/urls.py, pyarweb/urls.py
Dos detalles:
- cambié algunos links para que apunten acá también
- la app vieja no la borré, se sigue accediendo desde `/trabajo-vieja/`
=> Apunté /trabajo/ a la nueva app.

joboffers/templates/joboffers/joboffer_overview.html, requirements.txt
-  Los links de contacto de una oferta de trabajo son clickeables
- Closes #587 
- Prueba de los cambios en entorno local
- `make test`
1. Levantar el proyecto
2. Crear una oferta de trabajo con datos de contacto: mail, web y teléfono
3. Ingresar a la vista de detalle de la oferta y visualizar los datos de contacto
Gracias por contribuir con el proyecto.
Estamos pendiente de revisar los cambios propuestos.
=> Added link tags to contact info

events/tests/test_view_report_event.py, events/urls.py, events/views.py, templates/events/event_list.html
Un boton solo disponible para usuarios registrados y logueados,
- manda un mail a  admin@python.org.ar 
- Closes #463
=> Add event reporting feature with email notification to admin
